language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool -project MCUIViewLayoutExample/UIViewLayoutExample.xcodeproj -scheme "UIViewLayoutExampleTests" build test -sdk iphonesimulator

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals